### ISSUE TITLE
[FIX] Verificações antes do PC2

### ISSUE THREAD

**Issue by nszchagas** [Interacao-Humano-Computador/2022.2-Lichess#43]
- [x] O histórico de versão padronizado?
- [x] O(s) autor(es) e o(s) revisor(es) para cada artefato?
- [x] Vídeo de apresentação na categoria “não listado” no youtube;
- [x] Referências bibliográficas e/ou bibliografia em todos os artefatos;
- [x] As tabelas e imagens possuem legenda e fonte e elas chamadas dentro dos texto?
- [x] Um texto fazendo uma introdução dos artefatos?
- [x] O cronograma executado com quem realizou cada artefato/atividade com as datas de início e fim da construção/realização do artefato/atividade.
- [x] A(s) ata(s) da(s) reuniões (com data, horário de início e do final, participantes, objetivo, atividades definidas etc).
- [x] A gravação da reunião do grupo.
- [x] O perfil do usuário?
- [ ] O perfil do usuário segue os atributos de (Hackos e Redish, 1998; Courage e Baxter, 2005):
  - [ ] dados demográficos : idade, sexo, status socioeconômico;
  - [ ] experiência no cargo que ocupa: cargo atual, experiência nesse cargo, tempo na empresa, responsabilidades, trabalhos e cargos anteriores, plano de carreira;
  - [ ] informações sobre a empresa: tamanho da empresa, área de atuação;
  - [ ] educação: grau de instrução, área de formação, cursos realizados, alfabetismo. O quão bem o
usuário lê? Ele tem dificuldade com informação impressa? Tem experiência com textos complexos? Está disposto a ler texto ao utilizar produtos como o que está sendo projetado? Prefere aprender com outras pessoas? Prefere aprender fazendo?;  
  - [ ] experiência com computadores: alfabetismo computacional, habilidade com computadores, anos de experiência. Que sistemas computacionais o usuário conhece? Quais deles costuma utilizar? Que hardware costuma utilizar?;
  - [ ] experiência com um produto específico ou ferramentas semelhantes: experiência com produtos
concorrentes e outros produtos específicos do domínio, hábitos de uso, preferências e
descontentamentos;
  - [ ] tecnologia disponível: hardware (tamanho e resolução do monitor ou tela do dispositivo, velocidade
do processamento etc.), software e outras ferramentas aos quais tem acesso;
  - [ ] treinamento: o quanto o usuário valoriza treinamento? Prefere um estilo de aprendizado visual,
auditivo ou outro? Pode investir tempo aprendendo a utilizar o produto em questão?;
  - [ ] atitudes e valores: preferências de produto, medo de tecnologia etc. O usuário costuma assumir
riscos e explorar novas formas de fazer o mesmo trabalho? Ou evita novas experiências, preferindo
caminhos já percorridos e testados? Ou prefere que alguém lhes mostre cada passo de uma nova
tarefa sendo aprendida?;
  - [ ] conhecimento do domínio: o que e quanto o usuário conhece sobre o assunto em questão? É
especialista? É esperado que se torne um especialista?;
  - [ ] objetivos: quais são os principais objetivos dos usuário? Como eles são alcançados atualmente?;
  - [ ] tarefas: quais são as tarefas do usuário que precisam ser apoiadas? Quais dessas são
consideradas primárias, e quais são secundárias? Há quanto tempo realiza essas tarefas? São
tarefas frequentes ou infrequentes? São tarefas inovadoras? Que experiência ele possui em tarefas
semelhantes?;
  - [ ] gravidade dos erros: quais são as possíveis consequências negativas dos erros do usuário?;
  - [ ] motivação para o trabalho: o usuário se limita a cumprir a carga horária ou trabalha além do
expediente, por prazer? Gosta da interação social no local de trabalho? Tem ambição de ser
promovido?;
  - [ ] idiomas e jargões: que idiomas o usuário conhece e utiliza fluentemente? Ele possui um jargão
profissional particular, um vocabulário próprio da empresa, da sua atividade ou de algum grupo
social relevante para o seu projeto?
- [x] O perfil do usuário define os grupos de atributos apresentados no capítulo 8-Organização do Espaço de Problema:
  - [x] idade (criança, jovem, adulto, terceira idade etc.);
  - [x] experiência (leigo/ novato, especialista);
  - [x] atitudes (tecnófilos, tecnófobos); e
  - [x] tarefas primárias (compra, venda)
- [x] Considera aspectos Éticos de Pesquisas Envolvendo Pessoas?
- [x] Os 4 princípios (da autonomia, da beneficência, princípio da não maleficência e da justiça e equidade)
- [x] que solicitará a permissão para gravar a voz ou imagem de qualquer pessoa, antes de começar a gravação?
- [x] O termo de consentimento livre e esclarecido dos participantes?
- [ ] Foram utilizadas no mínimo duas técnicas para coletar dados e levantar os requisitos dos usuários
(quanto mais melhor)?
  - [ ] 1 entrevistas;
  - [ ] 2 grupos de foco;
  - [x] 3 questionários;
  - [ ] 4 brainstorming de necessidades e desejos dos usuários;
  - [ ] 5 classificação de cartões (card sorting);
  - [ ] 6 estudos de campo;
  - [ ] 7 investigação contextual.
- [x] As personas para o projeto?
- [x] As personas são definidas a partir dos dados do perfil do usuári0?
- [ ] As personas possuem?
  - [x] identidade: nome e sobrenome;
  - [x] idade e dados demográficos;
  - [x] foto;
  - [x] status: primária, secundária, outro stakeholder ou representa um antiusuário do seu sistema;
  - [x] objetivos: quais são os objetivos desta persona?
  - [x] habilidades: especialidade, educação, treinamento e competências específicas.
  - [x] tarefas: em linhas gerais, quais as tarefas básicas ou críticas que a persona realiza? Qual é a frequência, importância e duração dessas tarefas?
  - [x] relacionamentos: entender com quem a persona se relaciona é importante, pois ajuda a identificar outros stakeholders;
  - [x] requisitos: de que a persona precisa? Inclua citações que ajudam a dar mais vida a essas necessidades;
  - [x] expectativas: como a persona acredita que o produto funciona? Como ela organiza as informações no seu domínio ou trabalho?
- [ ] O elenco de personas? A razão da quantidade de personas é justificada?
- [ ] Os Cenários?
- [x] a Análise de tarefas?
- [x] Ao menos duas técnicas para especificar as tarefas?
  - [x] O HTA com diagrama, legenda e representação em tabela).
  - [x] GOMS (Goals, Operators, Methods, and Selection Rules) representado pelos modelos: KLM, CMN- GOMS, CPM-GOMS, CTT
- [x] Utilizaram alguma técnica para especificar as tarefas?

**Comment by Luckx98** [comment]
Falta um revisor no artefato de cronograma realizado, no geral ja está completo
